### ISSUE TITLE
Add more parameters to API wrapper

### ISSUE THREAD

**Issue by elhe26** [EddyVerbruggen/remove.bg#4]
Hi Eddy,

First, I'd like to thank you for creating this library. 

Could you please add the following parameters to the API:

### **roi**
(string)

Region of interest: Only contents of this rectangular region can be detected as foreground. Everything outside is considered background and will be removed. The rectangle is defined as two x/y coordinates in the format "<x1> <y1> <x2> <y2>". The coordinates can be in absolute pixels (suffix 'px') or relative to the width/height of the image (suffix '%'). By default, the whole image is the region of interest ("0% 0% 100% 100%"). 

### **crop**
(boolean)

Whether to crop off all empty regions (default: false). Note that cropping has no effect on the amount of charged credits. 

### **crop_margin**
(string)

Adds a margin around the cropped subject (default: 0). Can be an absolute value (e.g. "30px") or relative to the subject size (e.g. "10%"). Can be a single value (all sides), two values (top/bottom and left/right) or four values (top, right, bottom, left). This parameter only has an effect when "crop=true". The maximum margin that can be added on each side is 50% of the subject dimensions or 500 pixels. 

### **format**
(string)

Result image format: "auto" = Use PNG format if transparent regions exists, otherwise use JPG format (default), "png" = PNG format with alpha transparency, "jpg" = JPG format, no transparency, "zip" = ZIP format, contains color image and alpha matte image, supports transparency (recommended). 

### **bg_color**
(string)

Adds a solid color background. Can be a hex color code (e.g. 81d4fa, fff) or a color name (e.g. green). For semi-transparency, 4-/8-digit hex codes are also supported (e.g. 81d4fa77). (If this parameter is present, the other bg_ parameters must be empty.) 

### **bg_image_url**
(string)

Adds a background image from a URL. The image is centered and resized to fill the canvas while preserving the aspect ratio, unless it already has the exact same dimensions as the foreground image. (If this parameter is present, the other bg_ parameters must be empty.)

Regards,

**Comment by EddyVerbruggen** [comment]
Great idea! Please grab version 1.2.0 from npm and you're all set.
