### ISSUE TITLE
Add the new 'channels' and 'add_shadow' params to the API wrapper

### ISSUE THREAD

**Issue by mocabi** [EddyVerbruggen/remove.bg#5]
According to the latest [remove.bg/api](https://www.remove.bg/api) these two options were added: **channels** (string) and **add_shadow** (boolean).
Please add them to the wrapper.
Thank you for the awesome work!

**Comment by EddyVerbruggen** [comment]
Hi @mocabi, thanks for asking - I've just published version 1.3.0 to npm which includes this change. Also see the updated README.
